security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        matheo_userbundle:
            entity: { class: MatheoUserBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:            ^/
            anonymous:          true
            #switch_user:        false
            form_login:
                provider:       matheo_userbundle
                #csrf_provider: form.csrf_provider
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                default_target_path: /
                #use_forward:    false
                use_referer:    true
                failure_path:   null
            logout:
                invalidate_session: true
                path:           fos_user_security_logout
                target:         /
            oauth:
                resource_owners:
                    facebook:   "/connect/auth-facebook/"
                    google:     "/connect/auth-google/"
                login_path:     /login
                failure_path:   /login
                #target_path_parameter: _dest
                default_target_path: /
                use_forward:    false
                use_referer:    true
                oauth_user_provider:
                    service:    matheo.connect.user_provider
